/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cpu;

public final class R {
    public static final class array {
        public static final int test_arr=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int audio_imgpause=0x7f020000;
        public static final int audio_imgplay=0x7f020001;
        public static final int btn=0x7f020002;
        public static final int btn_active=0x7f020003;
        public static final int btn_disactive=0x7f020004;
        public static final int catatan=0x7f020005;
        public static final int compas=0x7f020006;
        public static final int directory_icon=0x7f020007;
        public static final int directory_up=0x7f020008;
        public static final int favicon=0x7f020009;
        public static final int file=0x7f02000a;
        public static final int file_icon=0x7f02000b;
        public static final int folder=0x7f02000c;
        public static final int folder_in=0x7f02000d;
        public static final int ic_menu_cookies=0x7f02000e;
        public static final int ic_menu_html=0x7f02000f;
        public static final int icon=0x7f020010;
        public static final int icon_apk=0x7f020011;
        public static final int icon_config=0x7f020012;
        public static final int icon_css=0x7f020013;
        public static final int icon_db=0x7f020014;
        public static final int icon_doc=0x7f020015;
        public static final int icon_gen=0x7f020016;
        public static final int icon_html=0x7f020017;
        public static final int icon_image=0x7f020018;
        public static final int icon_music=0x7f020019;
        public static final int icon_pdf=0x7f02001a;
        public static final int icon_php=0x7f02001b;
        public static final int icon_ppt=0x7f02001c;
        public static final int icon_txt=0x7f02001d;
        public static final int icon_video=0x7f02001e;
        public static final int icon_zip=0x7f02001f;
        public static final int iris=0x7f020020;
        public static final int red_mark=0x7f020021;
        public static final int setting=0x7f020022;
        public static final int trans=0x7f020023;
        public static final int transm=0x7f020024;
    }
    public static final class id {
        public static final int TextView01=0x7f080037;
        public static final int TextView02=0x7f080038;
        public static final int TextViewDate=0x7f080039;
        public static final int aButton=0x7f08000e;
        public static final int aEdit=0x7f08000d;
        public static final int alat=0x7f080059;
        public static final int alert_btnnf=0x7f080009;
        public static final int alert_cariOke=0x7f080001;
        public static final int alert_edCari=0x7f080000;
        public static final int alert_file_find_r=0x7f080005;
        public static final int alert_list=0x7f080002;
        public static final int alert_maju=0x7f080004;
        public static final int alert_mundur=0x7f080003;
        public static final int alert_nfed=0x7f080008;
        public static final int amButton=0x7f080007;
        public static final int amEdit=0x7f080006;
        public static final int audio_line1=0x7f08001c;
        public static final int audio_line2=0x7f08001d;
        public static final int audio_loading=0x7f080019;
        public static final int audio_playpause=0x7f08001e;
        public static final int audio_progress=0x7f08001a;
        public static final int audio_spinner=0x7f080018;
        public static final int audio_titleandbuttons=0x7f08001b;
        public static final int browser_hasil=0x7f080020;
        public static final int browser_url=0x7f08001f;
        public static final int btnLog_server=0x7f08004d;
        public static final int btnLog_server_mysql=0x7f08004c;
        public static final int btnLog_server_php=0x7f08004b;
        public static final int btnNext=0x7f08002a;
        public static final int btnPrev=0x7f080028;
        public static final int btnRefresh=0x7f080029;
        public static final int btn_Pdir=0x7f08003e;
        public static final int btn_Pmulut=0x7f08003d;
        public static final int btn_Ptelinga=0x7f08003c;
        public static final int btn_local=0x7f08003f;
        public static final int btn_okeC=0x7f080042;
        public static final int btn_panel=0x7f08002f;
        public static final int btn_server_root_dir=0x7f080046;
        public static final int btn_server_run_phpmyadmin=0x7f08004a;
        public static final int btn_server_site_editor=0x7f080048;
        public static final int btn_server_start=0x7f080044;
        public static final int disp=0x7f08004f;
        public static final int editText_docFolder=0x7f080010;
        public static final int editor_btnMenu=0x7f080033;
        public static final int editor_btnNext=0x7f080031;
        public static final int editor_btnPrev=0x7f080030;
        public static final int editor_btnRemove=0x7f08002e;
        public static final int editor_btnSave=0x7f080032;
        public static final int editor_editCode=0x7f080035;
        public static final int edt_negaraC=0x7f080041;
        public static final int edt_tempatC=0x7f080040;
        public static final int favicon=0x7f080024;
        public static final int fd_Icon1=0x7f080036;
        public static final int file_list=0x7f08003b;
        public static final int full_path=0x7f08003a;
        public static final int goto_url=0x7f080021;
        public static final int graph=0x7f080051;
        public static final int html_title=0x7f080025;
        public static final int image=0x7f080056;
        public static final int imageViewCompass=0x7f08002c;
        public static final int info_server_root_dir=0x7f080047;
        public static final int label_author=0x7f08004e;
        public static final int layout=0x7f080055;
        public static final int list_header=0x7f080013;
        public static final int list_image=0x7f080012;
        public static final int list_item=0x7f08000f;
        public static final int list_subheader=0x7f080014;
        public static final int main=0x7f08005a;
        public static final int main_btn=0x7f080017;
        public static final int main_edit=0x7f080016;
        public static final int main_status_power_text=0x7f080050;
        public static final int main_text=0x7f080015;
        public static final int progressBar_url_loading=0x7f080026;
        public static final int rg=0x7f08000a;
        public static final int rg1=0x7f08000b;
        public static final int rg2=0x7f08000c;
        public static final int riwList=0x7f080043;
        public static final int server_help=0x7f080049;
        public static final int server_info=0x7f080045;
        public static final int spinnerListFiles=0x7f08002d;
        public static final int terminal_input=0x7f080052;
        public static final int terminal_output=0x7f080054;
        public static final int terminal_submit=0x7f080053;
        public static final int text=0x7f080058;
        public static final int text1=0x7f08005b;
        public static final int thumbnail=0x7f080011;
        public static final int title=0x7f080057;
        public static final int toast=0x7f08005c;
        public static final int tvHeading=0x7f08002b;
        public static final int verticalNumsLine=0x7f080034;
        public static final int webTitlePanel=0x7f080023;
        public static final int webToolsPanel=0x7f080027;
        public static final int web_view=0x7f080022;
    }
    public static final class layout {
        public static final int alert_file=0x7f030000;
        public static final int alert_file_find_result=0x7f030001;
        public static final int alert_memori=0x7f030002;
        public static final int alert_newfile=0x7f030003;
        public static final int alert_telinga=0x7f030004;
        public static final int file_find=0x7f030005;
        public static final int input_field=0x7f030006;
        public static final int list_row=0x7f030007;
        public static final int main=0x7f030008;
        public static final int main_audio=0x7f030009;
        public static final int main_browser=0x7f03000a;
        public static final int main_compas=0x7f03000b;
        public static final int main_editor=0x7f03000c;
        public static final int main_fileexploler=0x7f03000d;
        public static final int main_filemanager=0x7f03000e;
        public static final int main_pengaturan=0x7f03000f;
        public static final int main_riwayat=0x7f030010;
        public static final int main_server=0x7f030011;
        public static final int main_status=0x7f030012;
        public static final int main_status_tasklist=0x7f030013;
        public static final int main_terminal=0x7f030014;
        public static final int notifi=0x7f030015;
        public static final int spinner_item=0x7f030016;
        public static final int toast=0x7f030017;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int disp_battery=0x7f070006;
        public static final int disp_cell=0x7f070003;
        public static final int disp_cpu=0x7f070004;
        public static final int disp_cpu_type=0x7f070005;
        public static final int disp_in=0x7f070009;
        public static final int disp_name=0x7f070007;
        public static final int disp_out=0x7f07000a;
        public static final int disp_system=0x7f07000c;
        public static final int disp_type=0x7f070008;
        public static final int disp_user=0x7f07000b;
        public static final int disp_wifi=0x7f070002;
        public static final int exists_processes=0x7f070010;
        public static final int hello_world=0x7f070001;
        public static final int help_server=0x7f070012;
        public static final int input_other_path=0x7f07000f;
        public static final int progress_dialog_message=0x7f070011;
        public static final int view_cookies=0x7f07000e;
        public static final int view_html=0x7f07000d;
    }
    public static final class style {
        public static final int AppTheme=0x7f060001;
        public static final int BtnStyle=0x7f060000;
    }
    public static final class xml {
        public static final int btn_nowplaying_background_small=0x7f040000;
        public static final int fon_title=0x7f040001;
        public static final int gradient_bg_1=0x7f040002;
        public static final int gradient_bg_2=0x7f040003;
        public static final int list_selector=0x7f040004;
        public static final int my_btn=0x7f040005;
        public static final int my_state_colors=0x7f040006;
        public static final int progress_horizontal=0x7f040007;
        public static final int seek_thumb=0x7f040008;
        public static final int tab_header=0x7f040009;
    }
}
