/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.cpu;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int btn_command=0x7f05000f;
        public static final int btn_curr=0x7f05000d;
        public static final int btn_panel=0x7f050004;
        public static final int editor_btnMenu=0x7f050008;
        public static final int editor_btnNext=0x7f050006;
        public static final int editor_btnPrev=0x7f050005;
        public static final int editor_btnSave=0x7f050007;
        public static final int editor_editCode=0x7f05000a;
        public static final int edt_command=0x7f050010;
        public static final int edt_curr=0x7f05000e;
        public static final int file_list=0x7f05000c;
        public static final int full_path=0x7f05000b;
        public static final int list_header=0x7f050002;
        public static final int list_image=0x7f050001;
        public static final int list_subheader=0x7f050003;
        public static final int thumbnail=0x7f050000;
        public static final int verticalNumsLine=0x7f050009;
    }
    public static final class layout {
        public static final int list_row_shun=0x7f020000;
        public static final int main_editor_shun=0x7f020001;
        public static final int main_filemanager_shun=0x7f020002;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int disp_battery=0x7f030006;
        public static final int disp_cell=0x7f030003;
        public static final int disp_cpu=0x7f030004;
        public static final int disp_cpu_type=0x7f030005;
        public static final int disp_in=0x7f030009;
        public static final int disp_name=0x7f030007;
        public static final int disp_out=0x7f03000a;
        public static final int disp_system=0x7f03000c;
        public static final int disp_type=0x7f030008;
        public static final int disp_user=0x7f03000b;
        public static final int disp_wifi=0x7f030002;
        public static final int exists_processes=0x7f030010;
        public static final int hello_world=0x7f030001;
        public static final int help_server=0x7f030012;
        public static final int input_other_path=0x7f03000f;
        public static final int progress_dialog_message=0x7f030011;
        public static final int view_cookies=0x7f03000e;
        public static final int view_html=0x7f03000d;
    }
    public static final class style {
        public static final int AppTheme=0x7f040000;
    }
}
